---
apps_packages:
  - brave-browser
  - btop
  - chromium
  - firefox
  - kitty
  - git
  - vim-default-editor

apps_repos:
  brave-browser: https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo

apps_rpms:
  code: https://code.visualstudio.com/sha/download?build=stable&os=linux-rpm-x64

# add apps_special_tailscale_authkey if you want to start the tailnet
# do not place this in git -- it's a password!
apps_special:
  - joplin
  - tailscale
  - uv
