---
argument_specs:
  main:
    options:
      fedora_use_apps:
        type: bool
        default: true
        description: Install and configure apps
      fedora_use_dotfiles:
        type: bool
        default: true
        description: Install and configure dotfiles
      fedora_use_fstab:
        type: bool
        default: true
        description: Setup /etc/fstab mounts
      fedora_use_niri:
        type: bool
        default: true
        description: Install and configure niri
      fedora_use_plymouth:
        type: bool
        default: true
        description: Install and configure plymouth
      fedora_use_sddm:
        type: bool
        default: true
        description: Install and configure SDDM
